[project]
name = "tech-writer-agent-dspy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "dspy-ai",
    "plotly",
    "pandas",
    "pathspec",
    "binaryornot",
    "sentence-transformers>=3.0.0"
]
